.TH REMASTER\-COMPOSE 1 2020\-03\-23 0.9.3 remaster\-iso

.SH NAME
remaster\-compose \- iso composition tool of remaster\-iso

.SH SYNOPSIS
\fBremaster\-compose\fR \f\[OPTIONS\]\fR

.SH DESCRIPTION
remaster\-compose \- iso composition tool for the remastering process of remaster\-iso.
.PP
remaster\-iso \- Set of scripts to assist remastering an iso image with custom settings for Debian based systems.

.SH OPTIONS
remaster\-compose \- See \-\-usage

.SH HOMEPAGE
More information about the remaster-iso project can be found at <\fIhttps://github.com/unixabg/remaster-iso\fR>.

.SH AUTHOR
remaster-iso was written by Richard Nelson <\fIunixabg@gmail.com\fR>.
