.TH REMASTER\-EXTRACT 1 2020\-08\-23 0.9.4 remaster\-iso

.SH NAME
remaster\-extract \- iso extraction tool of remaster\-iso

.SH SYNOPSIS
\fBremaster\-extract\fR \f\[OPTIONS\]\fR

.SH DESCRIPTION
remaster\-extract \- iso extraction tool for the remastering process of remaster\-iso.
.PP
remaster\-iso \- Set of scripts to assist remastering an iso image with custom settings for Debian based systems.

.SH OPTIONS
remaster\-extract \- See \-\-usage

.SH HOMEPAGE
More information about the remaster-iso project can be found at <\fIhttps://github.com/unixabg/remaster-iso\fR>.

.SH AUTHOR
remaster-iso was written by Richard Nelson <\fIunixabg@gmail.com\fR>.
